### PR TITLE
Support "Mebibytes" which is the full name of the MiB unit.

### PR DESCRIPTION
**Pull request by GrahamDennis**

### CODE REVIEW

**Comment by iamdanfox** [comment]
Seems like wikipedia just redirects!

image

**Review by iamdanfox — APPROVED** [review]

**Comment by carterkozak** [comment]
Nice catch!

**Comment by iamdanfox** [comment]
I'm gonna try and connect this repo to the rest of our infra shortly (to get changelog-app etc working).

**Comment by iamdanfox** [comment]
Separately, I think you should have write permissions to this repo (i.e. can just make a branch) rather than requiring a fork!

**Comment by GrahamDennis** [comment]
@iamdanfox No such luck:

```
08:43 $ git push
ERROR: Permission to palantir/human-readable-types.git denied to GrahamDennis.
fatal: Could not read from remote repository.
```

**Comment by iamdanfox** [comment]
Interesting. This repo is configured to give write access to everyone in https://github.com/orgs/palantir/teams/palantir-users/members, but I confirmed you're not in there.  Looking internally, I think `https://opensource.p.b/` is supposed to be the source of truth (and you _are_ on that list). @bluekeyes are we doing something wrong here? Is `Palantir Users` not syncing correctly?

**Comment by bluekeyes** [comment]
Team membership in this org is not managed automatically by any systems at this time. Can you raise an internal ticket if that's something we should be doing?

**Comment by iamdanfox** [comment]
ACK - looks like the internal page shows ~553 users and the actual oss palantir-users team shows 229 members... was that a manually curated list previously?

**Pull request merged**
